### PR TITLE
Candidates

### PR DESCRIPTION
**Pull request by dbrgn**

### CODE REVIEW

**Comment by dbrgn** [comment]
Should we also rename the "candidate" message to "candidates"?

**Comment by lgrahl** [comment]
Mhh, no I'm fine with _candidate_. If you want it, change it. :)

**Comment by dbrgn** [comment]
I think it would make sense, as the thing being sent is a list of candidates :)

**Comment by dbrgn** [comment]
Renamed. @lgrahl can we merge this PR?

**Comment by dbrgn** [comment]
I also noticed that we were using camel case instead of underscores :)

**Comment by lgrahl** [comment]
I would leave those fields camelCased so you can use the object directly in JS without any need to reconstruct it. Makes it a lot easier for the user application.

**Comment by dbrgn** [comment]
Ah, I see. On the other hand it's inconsistent with the rest of the protocol.

Should I convert it back to camel case and add a note?

**Comment by lgrahl** [comment]
Yeah, it's inconsistent, I should have left a note.

> Should I convert it back to camel case and add a note?

:+1:

**Comment by dbrgn** [comment]
@lgrahl better now?

**Review by lgrahl — APPROVED** [review]

**Pull request merged**
