### PR TITLE
Ping interval

### PR DESCRIPTION
**Pull request by lgrahl**
As a result of https://github.com/saltyrtc/saltyrtc-server-python/pull/44

@dbrgn Please review.

### CODE REVIEW

**Comment by dbrgn** [comment]
The wording is a bit unclear to me. What is "a very long interval"? Why does the server send pings if the client requests that no ping messages SHOULD be sent?

I'd simply leave that area unspecified. I'd keep the change on line 613 (SHALL -> SHOULD) and get rid of `If the value is`0`, the server SHALL NOT send WebSocket *ping* messages to the client.`.

**Comment by lgrahl** [comment]
I do not want to remove that line. It's good to be precise about the `0` case on the server's side as well. The _SHOULD_ indicates that this is a best effort service and server implementations may deviate slightly.

**Comment by lgrahl** [comment]
@dbrgn Please, have a quick look at the changes.

**Comment by dbrgn** [comment]
Ok, fine with me now!

**Pull request merged**
