### PR TITLE
Add WebSocket close code 1000

### PR DESCRIPTION
**Pull request by dbrgn**
It was missing :slightly_smiling_face:

### CODE REVIEW

**Comment by lgrahl** [comment]
I guess that's because we don't use it (or do we?).

> The following close codes **are being used** by the protocol

**Comment by dbrgn** [comment]
Ah, I see. You're right :)

We use it in Threema as close code when closing the connection (with relayed data there's no handover so we can't use 3003), but the protocol itself does not use it.

I wonder if we should still list it though, since it's the right choice when closing a connection with neither an error condition nor a handover?

**Comment by lgrahl** [comment]
I don't have a strong opinion on this. Feel free to merge or close. :smile_cat: 

But be aware there are many other close codes: https://tools.ietf.org/html/rfc6455#section-7.4.1

**Comment by dbrgn** [comment]
> But be aware there are many other close codes

Yes, but 1000 is by far the most important one.

I think it would be helpful to include it on the list.

**Pull request merged**
