### PR TITLE
Add 'disconnected' message type

### PR DESCRIPTION
**Pull request by dbrgn**
Open questions:

- Should this be sent for all close reasons, even if the client disconnects due to handover?
- Should the server include the close reason in the disconnect message?

### CODE REVIEW

**Review by lgrahl — APPROVED** [review]
> Should this be sent for all close reasons, even if the client disconnects due to handover?

Yes, let's not apply any logic in the server. Handover may have an entirely different meaning for other tasks in the future - who knows. :smiley: 

> Should the server include the close reason in the disconnect message?

I don't think so. If that information is necessary for an application, it should just use the 'close' message. If it doesn't get a 'close' message prior to a 'disconnected' message, then it should be fairly obvious it's a non-graceful disconnect.

**Comment by dbrgn** [comment]
Good points :)

**Comment by lgrahl** [comment]
This is a breaking change in `v1`... we are in kind of a limbo state where we haven't officially released `v1` but the document already states it is at `v1`. As long as there are no other known SaltyRTC implementations, I'd say this is fine. But we should be more careful next time.

**Comment by dbrgn** [comment]
Yeah, I thought about that and came to the same conclusion. On the other hand we state that releases will be marked with git tags, and we haven't pushed any of those. So technically it's not at version 1.0 yet.

**Pull request merged**
